### PR TITLE
Add measured/observed properties to network components

### PR DESCRIPTION
**Pull request by csweetapple**
Add measured properties to junctions, tanks, reservoirs, pipes, pumps and valves (each with a relationship to the Device that provides the measurement). 

Properties for inclusion inititially guided by those simulated in EPANET. Refinement probably required - e.g. instead of 'quality', need specific substances that could be measured?

### CODE REVIEW

**Comment by albertoabellagarcia** [comment]
1) the idea is perfectly right.
2) The spec modification no longer makes sense as long as the specifications will be generated automatically
3) The definition of the properties are not acceptable (all the properties are the same)
4) It does not include the descriptions for every property (new requirement for the json schemas)
BESt

**Comment by albertoabellagarcia** [comment]
1) spec modifications no longer makes sense and the descriptions should be included in the descriptions in the json schema. 
2) thus pipe, pump tank and valve should be reviewed.

**Comment by csweetapple** [comment]
@albertoabellagarcia - is this better? I've revised the definition of the new properties and made sure they have a description in the schema. I've tried to check the schema with the data models contribution API, but it just gives me a blank page...
I haven't added descriptions for properties that were previously present in the data model and haven't been modified in this PR, since that's beyond the scope of this issue.

**Comment by albertoabellagarcia** [comment]
All of you are PR is quie valuable, only a minor issue with the WaterNetworkManagement-schema.json because the validation schema you PR is for the normalized payload and not for keyvalues payload, which is the chosen one for the initiative. Let me put an example
You provide this for pressure
 "pressure": {
            "type": "object",
            "description": "Observed pressure at the node (junction, tank or reservoir)",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "Property"
                    ]
                },
                "value": {
                    "type": [
                        "number",
                        "string"
                    ]
                },
                "unitCode": {
                    "type": "string"
                },
                "observedBy": {
                    "type": "object",
                    "description": "Relationship to the entity providing the pressure value",
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": [
                                "Relationship"
                            ]
                        },
                        "object": {
                            "type": [
                                "string"
                            ],
                            "format": "uri"
                        }
                    }
                },
                "observedAt": {
                    "type": "string",
                    "format": "date-time"
                }
            },
But the right version is much, much simpler because
1.- None of internal parameters are in the data model
2.- The 'value' and 'type' does not appear in keyvalues (I guess it is a simple value and not an array, isn't it?), accordingly 
 "pressure": {
             "type": "number",
            "description": "Property. Observed pressure at the node (junction, tank or reservoir). Model:''https://schema.org/Number. Units:'liters per second'"
}
I have a doubt about observedBy (this was the case of bein a property of property, the the right one should be:
 "pressure": {
             "type": "object",
            "description": "Property. Observed pressure at the node (junction, tank or reservoir). Model:''https://schema.org/Number. Units:'liters per second'"
"properties":{
"value"{
"type2: "Number"
},
"observedBy":{
"anyOf": [
        {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[\\w\\-\\.\\{\\}\\$\\+\\*\\[\\]`|~^@!,:\\\\]+$",
          "description": "Property. Identifier format of any NGSI entity"
        },
        {
          "type": "string",
          "format": "uri",
          "description": "Property. Identifier format of any NGSI entity"
        }
      ],
"description": "Relationship. Relationship to the entity providing the pressure value"
}
}
}

https://bit.ly/contribution_manual

**Review by albertoabellagarcia — APPROVED** [review]
I'll make a small correction in the shared elements.

**Comment by bobeal** [comment]
It seems good for NGSI-LD representation of the model. About the JSON schema, I'm not enough expert, maybe @AHABID can provide feedback about it?

**Review by albertoabellagarcia — APPROVED** [review]
Plenty of changes

**Pull request merged**
