### PR TITLE
contribution from Water DNA project in South Korea

### PR DESCRIPTION
**Pull request by IoTKETI**
From the Water DNA project in South Korea, we suggest to extend existing models with new attributes:
- WaterPipe, Tank, Pump
and also propose a new model to this subject:
- WaterPumpStation

### CODE REVIEW

**Comment by eladsal** [comment]
Thank you @IoTKETI for this contribution. 

Can you please explain in words what are the edits you have made to the pipe, tank, and pump elements?
As for the pumping station, although EPANET does not support such an object, I can see how it can be useful. Can you please clarify what is the pump station intake? Also, would you consider adding to the station a reference to the pump objects in it, and the suction and discharge junctions?

**Comment by albertoabellagarcia** [comment]
I guess that this contribution should be placed in a different subject [WaterDistribution](https://github.com/smart-data-models/dataModel.WaterDistribution/tree/master) because the data models in this subject are oriented to be used with EPANET simulation tool. If they provide something useful for EPANET, then keep them, if not, then move to this other subject.

the two new data models, Waterprocess and Wwaterpumpstation can be simulated in EPANET? 

Last but not least, context.jsonld is generated automatically from the terms in the project, if you want to customize the IRI you can use notes_context.jsonld (see [contribution manual](https://bit.ly/contribution_manual))  and eventually [the service for this customization](https://smartdatamodels.org/index.php/generate-acontext-based-on-external-ontologies-iris/) see [this video](https://www.youtube.com/watch?v=Za9fChSn9yg) for further support. If you are just extending the @context with the new terms, it is not necessary, they are added automatically

**Comment by ooosm** [comment]
Hi, thank you two gentlemen for the feedback, questions and the suggestions. 

Here are my answers:
1. We chose this model because the WaterDistributionManagementEPANET models fits much better for our models, though as you mentioned not everything is regarding the EPANET simulations. The WaterDistribution model is, at the moment, only has WaterDistributionNetwork model which is not suitable for our contributions.

2. While WaterPumpStation has the implementation on EPANET, while the WaterProcess is in the domain of water purification/treatment, it is done by another simulator than EPANET.

3. Sorry about the over-populated change requests that are shown on the github. This is all about auto-indent / lint stuff onn my VS Code. Indent changes are not shown as modifications in my commit, but on the github... 

4. With that(3), new attributes from our pull requests are as the following:
  - WaterPipe: waterLevel, waterPressure
  - Tank: volume
  - Pump: ppumpCapacity

5. regarding the context.jsonld file, yeah, it was not on the guide. So should I pull out those additions by myself or should I keep that in my mind from the next time?

**Comment by IoTKETI** [comment]
Hi, thank you two gentlemen for the feedback, questions and the suggestions. 

Here are my answers:
1. We chose this model because the WaterDistributionManagementEPANET models fits much better for our models, though as you mentioned not everything is regarding the EPANET simulations. The WaterDistribution model is, at the moment, only has WaterDistributionNetwork model which is not suitable for our contributions.

2. While WaterPumpStation has the implementation on EPANET, while the WaterProcess is in the domain of water purification/treatment, it is done by another simulator than EPANET.

3. Sorry about the over-populated change requests that are shown on the github. This is all about auto-indent / lint stuff onn my VS Code. Indent changes are not shown as modifications in my commit, but on the github... 

4. With that(3), new attributes from our pull requests are as the following:
  - WaterPipe: waterLevel, waterPressure
  - Tank: volume
  - Pump: pumpCapacity

5. regarding the context.jsonld file, yeah, it was not on the guide. So should I pull out those additions by myself or should I keep that in my mind from the next time?

**Comment by eladsal** [comment]
Thank you, @IoTKETI for your response.
Can you please explain more about the suggested additions? What is the `water level` for a pipe? One of the main assumptions in EPANET is that the pipes are full (entire cross-section). This is not a drainage pipe. Furthermore, what is the `water pressure` of a pipe? The water pressure is measured at a point, so where in the pipe? It can change along the length of the pipe.
And, `pump capacity`, is it the maximum flow of the pump\station?

**Comment by IoTKETI** [comment]
Hi @eladsal  thanks for your further clarification questions.

As a small background, I'm an IoT/smart city guy so I talked to the water domain expert who worked with in the Water DNA project.

Short introduction on our project should be described first so you can better understand our proposals. In our project, we built the system that integrates water distribution network and sewerage network in terms of simulation (EPANET and SWMM) and real-time data exchange with our data platform (i.e. Water DNA) over NGSI-LD APIs.

1) water level

This is why we suggested something regarding sewerage network like water level in the Pipe model. Currently, I don't see SWMM or sewerage network compatible data models or subjects. If we could evolve EPANET model into a universal simulation model for entire water domain, it should be useful to have water level and pressure for the Pipe.

2) water pressure
Pressure as measured by the pressure meter, it can be installed in the middle of the pipe or at the junction between pipes.

3) pump capacity
The term we chose was a bit misleading so I'd like to propose the different name "intakeFlow" (m"3/min) which is a measured intake flow at a certain time. We propose this attribute for the NEW PumpStation model, and the PumpStation as a facility has one or more Pumps. We'd add this aspects as well as the intakeFlow for the revision, if you agree on the concept.

Thanks!

**Comment by albertoabellagarcia** [comment]
I have non-expert EPANET question, Can these attributes, water level, water pressure, and pump capacity be ingested in a EPANET simulaton?
If yes, we'll accept the contribution immediately.
If not, then we should move the contribution to another repository ([waterdistribution](https://github.com/smart-data-models/dataModel.WaterDistribution/)) is the right candidate.
If it is not clear, let's arrange a call on how to face it.

**Comment by IoTKETI** [comment]
@albertoabellagarcia @eladsal 

I guess it depends on how do we manage the EPANET data model for the future. 

option 1) Even the name is EPANET, which is the "SUBJECT" name, not the data model type/name itself, we extend the modeling views to include SWMM related aspects (e.g. water level in the Pipe) as suggested by KETI. The intent is to focus on each models, while the subject name serves as the context. (I'm not saying that we can ignore the subject).

option 2) Keep it pure EPANET and all subsequent models.

As the contributor, I'd suggest to go with option 1. Also in the waterDistribution subject, the only model is WaterDistributionNetwork which does not distinguish/split lower level models, but have all aspects/properties in one single model. Many of the attributes are bound to a tank (e.g. level, pressure), but in the general water distribution network, there are other stuffs like pipe, junctions just like the virtual world in EPANET.

Your thoughts?

**Comment by eladsal** [comment]
Hi @IoTKETI, I think the question is, why not just go with an SWMM model? It differs from EPANET and has different model elements (conduits, street inlet drains, storage/treatment units, flow dividers, pumps, weirs, etc.).

I am happy to jump on a call if needed.

**Comment by IoTKETI** [comment]
Hi @eladsal 

Yeah, the conf. call should be easier to discuss. I'll send you the email to you to arrange the quick meeting today. This conversation is public so, over the email for that.

**Comment by albertoabellagarcia** [comment]
I'd like to know if the meeting is being held. Did you? My availability is here [https://calendly.com/smartdatamodels
](https://calendly.com/smartdatamodels)

**Comment by albertoabellagarcia** [comment]
WaterProcess [has already been published](https://smartdatamodels.org/index.php/waterporcess-new-datamodel-wastewater-subject/). 
The rest of the commit according to the conversation should be either in a new subject (then use the [incubated repository](https://github.com/smart-data-models/incubated/tree/master/SMARTWATER/WATERDNA))  or in [waterDistribution](https://github.com/smart-data-models/dataModel.WaterDistribution/) subject. 
Please move the PR to any of these options.

**Pull request closed without merging**
